First MVC Application/Models/DogViewModel.cs
namespace First_MVC_Application.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }

    }
}

First MVC Application/Models/ErrorViewModel.cs
namespace First_MVC_Application.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

First MVC Application/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using First_MVC_Application.Models;

namespace First_MVC_Application.Controllers
{
    public class HelloWorldController : Controller
    {
        private static List<DogViewModel> dogs = new List<DogViewModel>();

        public IActionResult Index()
        {

/*
            DogViewModel doggo = new DogViewModel()
            {
                Name = "Tom",
                Age = 2
            };*/
            return View(dogs);
        }
      
        public IActionResult Create()
        {
            var dogVm = new DogViewModel();
            return View(dogVm);
        }

        public IActionResult RegisterDog(DogViewModel dogViewModel)
        {
            /*return View("Index");*/

            dogs.Add(dogViewModel);
            return RedirectToAction(nameof(Index));
        }

    }
}

First MVC Application/Controllers/HomeController.cs
using First_MVC_Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace First_MVC_Application.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

First MVC Application/Views/HelloWorld/Create.cshtml
@model DogViewModel

<h1 class="text-center">Dog Registration</h1>  
<hr style="height:0.5px"/>


<div class="row justify-content-center">
    <div class="col-6">
            <div class="card">
                 <div class="card-header">
                     <h5>Register your dog</h5>
                </div>
                <div class="card-body">
                    <form asp-controller="HelloWorld" asp-action="RegisterDog" method="post">
                        <div class="mb-3">
                            <label class="form-label">Dog's Name</label>
                            <input asp-for=Name type="text" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Age</label>
                            <input asp-for=Age type="number" max="10" min="1" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>

                <div class="card-footer">  
                    
                </div>
           
           

        </div>

        
    </div>
</div>

First MVC Application/Views/HelloWorld/Index.cshtml
@model List<First_MVC_Application.Models.DogViewModel>

<h1>Registered Dogs</h1>
<p>Here's the list you created...</p>

<ul>
@foreach(var dog in Model)
{
 <li>@dog.Name (@dog.Age)</li>   
}
</ul>

First MVC Application/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

First MVC Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - First_MVC_Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/First_MVC_Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://ggsc.s3.amazonaws.com/images/uploads/The_Science-Backed_Benefits_of_Being_a_Dog_Owner.jpg" alt="Dog" width="100px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Registration</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - First_MVC_Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>